version: 2.0
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout

      - run:
          name: Compile & Make pdf
          command: |
            cd C92 &&
            uplatex content.tex &&
            dvipdfm content.dvi &&
            cd ..

      - run:
          name: setup  git
          command: | 
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apk add --no-cache bash git openssh
              mkdir ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts
            fi
      - deploy:
          name: Deploy nodels
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "＿人人人人＿" &&
              echo "＞　 更新　＜" &&
              echo "￣Y^Y^Y^Y￣" &&
              echo "" &&
              ./tools/auto-commit.sh
            fi

