version: 2.0
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run:
          name: Compile & Make pdf
          command: |
            cd C92 &&
            uplatex content.tex &&
            dvipdfm content.dvi

      - deploy:
          name: Deploy nodels
          command: echo "ToDo (ToT)"
